language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t dime2lo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dime2lo/docker-react npm run test