language: generic
sudo: required
services:
  - docker

before install:
  - docker build -t dime2lo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dime2lo/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "udocker"
  env: "Udocker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-433434055790"
  bucket_path: "udocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
